# Generated by Django 5.1.5 on 2025-02-03 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marraige_date", models.CharField(max_length=20, null=True)),
                ("couple_names", models.CharField(max_length=255, null=True)),
                ("card_text", models.TextField(null=True)),
                ("card_images", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("surname", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=12)),
                ("date", models.DateField(auto_now=True)),
                ("guests", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=30)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CoupleMoments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=50)),
                ("couple_image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gallery_images", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Packages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("detail_description", models.TextField()),
                ("price", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_image", models.ImageField(upload_to="images/")),
                ("service_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Photography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                (
                    "service_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Eventapp.services",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ocassion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
                ("description", models.TextField(blank=True, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                (
                    "service_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Eventapp.services",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Decoration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=30)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                (
                    "service_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Eventapp.services",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                (
                    "service_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Eventapp.services",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeddingGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("heading_image", models.ImageField(blank=True, upload_to="images")),
                ("images", models.ImageField(blank=True, upload_to="images/")),
                (
                    "names",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Eventapp.couplemoments",
                    ),
                ),
            ],
        ),
    ]
